import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dirname, "../../..");
const outputPath = resolve(
  repositoryRoot,
  "runtime/agent-fabric/src/daemon/runtime-build-identity.generated.ts",
);

async function sourceFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) files.push(...await sourceFiles(path));
    else if (entry.isFile() && path.endsWith(".ts") && !path.endsWith("runtime-build-identity.generated.ts")) files.push(path);
  }
  return files;
}

async function buildIdentity(): Promise<string> {
  const inputs = [
    "package.json",
    "package-lock.json",
    "tsconfig.json",
    "runtime/agent-fabric/package.json",
    "runtime/agent-fabric/tsconfig.json",
    "runtime/agent-fabric/tsconfig.build.json",
    "runtime/agent-fabric-protocol/package.json",
    "runtime/agent-fabric-protocol/tsconfig.json",
    "runtime/agent-fabric-protocol/tsconfig.build.json",
    "runtime/agent-fabric/scripts/generate-runtime-build-identity.ts",
    ...(await sourceFiles(resolve(repositoryRoot, "runtime/agent-fabric/src"))),
    ...(await sourceFiles(resolve(repositoryRoot, "runtime/agent-fabric-protocol/src"))),
  ].map((path) => resolve(repositoryRoot, path));
  const digest = createHash("sha256");
  for (const path of [...new Set(inputs)].sort()) {
    digest.update(relative(repositoryRoot, path));
    digest.update("\0");
    digest.update(await readFile(path));
    digest.update("\0");
  }
  return `sha256:${digest.digest("hex")}`;
}

export async function generateRuntimeBuildIdentity(): Promise<{
  identity: string;
  changed: boolean;
}> {
  const identity = await buildIdentity();
  const rendered = `// Generated by \`scripts/agent-fabric-warm\`. Do not edit by hand.\nexport const RUNTIME_BUILD_IDENTITY =\n  \"${identity}\";\n`;
  let current: string | undefined;
  try {
    current = await readFile(outputPath, "utf8");
  } catch (error: unknown) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
  }
  if (current === rendered) return { identity, changed: false };
  await writeFile(outputPath, rendered, "utf8");
  return { identity, changed: true };
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === import.meta.filename) {
  const result = await generateRuntimeBuildIdentity();
  process.stdout.write(`${result.changed ? "updated" : "unchanged"} ${result.identity}\n`);
}
