import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import type { Sha256Digest } from "../src/review/canonical/index.js";
import {
  computeReviewProfileCatalogueSnapshot,
} from "../src/review/profile/catalogue-digest.js";

const repositoryRoot = resolve(import.meta.dirname, "../../..");

function generatedSource(digest: Sha256Digest, profileDocumentDigest: Sha256Digest): string {
  return `// Generated by \`npm run profile:catalogue:pin\`. Do not edit by hand.
import type { Sha256Digest } from "../canonical/index.js";

export const REVIEW_PROFILE_CATALOGUE_DIGEST: Sha256Digest =
  "${digest}";

export const REVIEW_PROFILE_DOCUMENT_DIGEST: Sha256Digest =
  "${profileDocumentDigest}";
`;
}

export async function pinReviewProfileCatalogueDigest(options: {
  readonly repositoryRoot?: string;
  readonly outputPath?: string;
} = {}): Promise<{
  path: string;
  digest: Sha256Digest;
  profileDocumentDigest: Sha256Digest;
  changed: boolean;
}> {
  const root = resolve(options.repositoryRoot ?? repositoryRoot);
  const path = resolve(options.outputPath
    ?? `${root}/runtime/agent-fabric/src/review/profile/catalogue-digest.generated.ts`);
  const { digest, profileDocumentDigest } = await computeReviewProfileCatalogueSnapshot(root);
  const rendered = generatedSource(digest, profileDocumentDigest);
  let source: string | undefined;
  try {
    source = await readFile(path, "utf8");
  } catch (error: unknown) {
    if (
      typeof error !== "object" ||
      error === null ||
      !("code" in error) ||
      error.code !== "ENOENT"
    ) throw error;
  }
  const changed = source !== rendered;
  if (changed) await writeFile(path, rendered, "utf8");
  return { path, digest, profileDocumentDigest, changed };
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === import.meta.filename) {
  if (process.argv.length !== 2) {
    throw new Error("usage: npm run profile:catalogue:pin");
  }
  const result = await pinReviewProfileCatalogueDigest();
  process.stdout.write(`${result.changed ? "updated" : "unchanged"} ${result.path} ${result.digest}\n`);
}
