// Generated by `npm run profile:catalogue:pin`. Do not edit by hand.
import type { Sha256Digest } from "../canonical/index.js";

export const REVIEW_PROFILE_CATALOGUE_DIGEST: Sha256Digest =
  "sha256:5affe1fb055b1ee0226b3326942411c0a4e456eb145618375d72abf1e3203f04";

export const REVIEW_PROFILE_DOCUMENT_DIGEST: Sha256Digest =
  "sha256:d082739f69a62e1705ed8521d9f2f0511a981edd3413c85b6f61b3a9a8fb4fae";
